--CONST_SECOND_SCENE = IIF(Debug.IsOn, "debugMenu", "tilemap")
CONST_SECOND_SCENE  = "mapScene"
CONST_INIT_MAP = "ext/data/maps/tutorial_map001.lua"

-- UI constants
CONST_WIDGET_UI_CONSOLA = "UI_WIDGET_CONSOLA"
CONST_WIDGET_UI_TEXTBOX = "UI_WIDGET_TEXTBOX"
CONST_WIDGET_UI_TOOLTIP = "UI_WIDGET_TOOLTIP"

-- Observer constants
CONST_OBSERVE_UI_UPDATE = "UI_UPDATE"
CONST_OBSERVE_UI_DRAW = "UI_DRAW"
CONST_OBSERVE_UI_KEYPRESS= "UI_KEYPRESS"
CONST_OBSERVE_UI_TEXTINPUT= "UI_TEXTINPUT"

CONST_OBSERVE_UI_ADD_CONSOLE_TEXT = "UI_CONSOLE_ADDTEXT"

CONST_OBSERVE_GAMEPLAY_TILE_CHANGED = "GAMEPLAY_TILE_CHANGED"

-- Input constants
CONST_INPUT_EXIT = "EXIT"
CONST_INPUT_CONSOLE = "CONSOLE"
CONST_INPUT_LEFT = "LEFT"
CONST_INPUT_RIGHT = "RIGHT"
CONST_INPUT_UP = "UP"
CONST_INPUT_DOWN = "DOWN"

Filesystem = require("lib.io.filesystem")
